baseURL = "https://cicdsecurity.ajl.sa-demos.net"
languageCode = "en-GB"
defaultContentLanguage = "en"

title = "Build Security In - Workshop Guide"
theme = "aws_workshop_theme"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/ajlanghorn/aws-ako20-cicd-security"
  author = "Andrew Langhorn, Chris King"
  description = "Workshop guide for Build Security In session"
  showVisitedLinks = false
  disableSearch = false
  disableAssetsBusting = false
  disableInlineCopyToClipBoard = true
  disableShortcutsTitle = false
  disableLanguageSwitchingButton = false
  disableBreadcrumb = true
  disableNextPrev = false
  ordersectionsby = "weight"
  themeVariant = "aws"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Build Security In - Workshop Guide"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-aws'></i> AWS Console"
url = "https://console.aws.amazon.com/"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Hugo Documentation"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

#Delete or comment out the Below to remove any second Languages.  If you wish to use second languages you must add the menu items again and also create alternative files for each page titled with the language code such as index.fr.md
#[Languages.fr]
#title = "Documentation du thème Hugo Learn"
#weight = 2
#languageName = "Français"

#[[Languages.fr.menu.shortcuts]]
#name = "<i class='fab fa-fw fa-github'></i> Repo GitHub"
#identifier = "ds"
#url = "https://github.com/matcornic/hugo-theme-learn"
#weight = 10

#[[Languages.fr.menu.shortcuts]]
#name = "<i class='fas fa-fw fa-camera'></i> Vitrine"
#url = "/showcase"
#weight = 11

#[[Languages.fr.menu.shortcuts]]
#name = "<i class='fas fa-fw fa-bookmark'></i> Documentation Hugo"
#identifier = "hugodoc"
#url = "https://gohugo.io/"
#weight = 20

#[[Languages.fr.menu.shortcuts]]
#name = "<i class='fas fa-fw fa-bullhorn'></i> Crédits"
#url = "/credits"
#weight = 30
