baseURL = "http://cicdsecurity.ajl.sa-demos.net"
languageCode = "en-GB"
defaultContentLanguage = "en"

title = "Build Security In - Workshop Guide"
theme = "aws_workshop_theme"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/ajlanghorn/aws-ako20-cicd-security"
  author = "Andrew Langhorn, Chris King"
  description = "Workshop guide for Build Security In session"
  showVisitedLinks = false
  disableSearch = true
  disableAssetsBusting = false
  disableInlineCopyToClipBoard = true
  disableShortcutsTitle = false
  disableLanguageSwitchingButton = false
  disableBreadcrumb = true
  disableNextPrev = false
  ordersectionsby = "weight"
  themeVariant = "aws"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Build Security In - Workshop Guide"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-aws'></i> AWS Console"
url = "https://console.aws.amazon.com/"
weight = 11
